### PR TITLE
Fix installation with Mincer 1.3

### PR DESCRIPTION
**Pull request by tortuetorche**
Otherwise, I get this error:

```
npm ERR! peerinvalid The package mincer does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mincer-babel@0.0.3 wants mincer@~1.2
```

I don't know why I've this issue, the version constraint `~1.2` looks good but apparently it doesn't work correctly, maybe a `npm` bug.

By the way, I also get these warning messages:

```
npm WARN peerDependencies The peer dependency mincer@~1.2 included from mincer-babel will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

Maybe you should move the `peerDependencies` to the `dependencies` option?

Cheers,
Tortue Torche

### CODE REVIEW

**Comment by netsgnut** [comment]
BTW just a heads-up: in our case Mincer 1.3 is not really particularly different from Mincer 1.2 in terms of API - the version is bumped because they have to inform of the requirement of `postcss` as a new dependency for those who require `autoprefixer` or `csswring`, of which both of them Babel has nothing to do with, i.e. safe to upgrade.

**Comment by tortuetorche** [comment]
Why not, @ssar could publish a 0.0.4 version with this pull request and this [one](https://github.com/ssar/mincer-babel/pull/3), then he could push a 0.1.0 version with Mincer 1.3 as a minimum requirement.

**Comment by ssar** [comment]
Thanks @tortuetorche for the pull request.
If the mincer-1.3 API is compatible, I think it's best if I  just change the peerDepencency to "mincer": "~1.2 || ~1.3" and create a 0.0.4 patch release.

**Comment by tortuetorche** [comment]
Many thanks Simon! I updated my [`larasset-js`](https://github.com/efficiently/larasset-js/tree/1.1) module to support ES2015 with the help of your Mincer engine.

**Pull request closed without merging**
